# Generated by Django 3.2 on 2021-05-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentName', models.CharField(choices=[('Si', 'Sum Insured'), ('rt', 'Rate'), ('Tn', 'Tenure')], max_length=200)),
                ('componentValue', models.CharField(max_length=200)),
                ('selectionDateTime', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcal.member')),
            ],
        ),
    ]
